### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by harisankarsadasivan** [joshidhaivat/QAlign#2]
Output quantized reads are not produced. Program is faulty.

**Comment by joshidhaivat** [comment]
That's a bit strange. The program is providing correct output. Can you please send me the command you are using?
Also, I have made a few modifications to the code to make sure that the command is used properly with all the necessary inputs. You can check the example for converting the nucleotide sequence to quantized sequence (Q2).

Please try downloading QAlign again and let me know if you face any issues.

Thanks,
Dhaivat
