### ISSUE TITLE
working with real  MiniON outputs (multiple fasqfiles)

### ISSUE THREAD

**Issue by dieunelderilus** [joshidhaivat/QAlign#3]
Dear Qalign developer - This software takes as input a fasta file to generate and convert it to its quantized version.  When I am sequencing one gene or a region of the gene (amplicons) with nanopore technology,  I get several fastq files for the same sample ID.   Should I concatenate the files, convert this to fasta format and provide this last one as input to the 'qalign/main.py' script?

Thank you!
~DD

**Comment by joshidhaivat** [comment]
Yes, that should work as long as the input to Qalign is in fasta format.
